export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_RECIPES = "FETCH_RECIPES";
export const FETCH_FAVORED_RECIPES = "FETCH_FAVORED_RECIPES";
export const UPDATE_FAVORITE = "UPDATE_FAVORITE";
